spring:
  application:
    name: Owing-Api

  profiles:
    default: local
    active: local
    group:
      local: infrastructure, domain-entity, domain-node, common
      test: infrastructure, domain-entity, domain-node, common

---

spring:
  config:
    activate:
      on-profile: local

---

spring:
  config:
    activate:
      on-profile: test

---

springdoc:
  swagger-ui:
    path: /swagger-ui.html
google:
  oidc:
    audience: ${GOOGLE_OIDC_AUDIENCE}
jwt:
  secret: ${JWT_SECRET_KEY}