spring:
  config:
    import: optional:file:.env[.properties]

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  timeout: 5000

cloud:
  aws:
    region: ${AWS_REGION}
    credentials:
      access-key: ${IAM_ACCESS_KEY}
      secret-key: ${IAM_SECRET_KEY}
  s3:
    bucket: ${S3_BUCKET}

#cloud:
#  aws:
#    s3:
#      bucket: ${BUCKET_NAME}
#      directory:
#        project: ${DIRECTORY_PROJECT}
#        casting: ${DIRECTORY_CASTING}
#        universe: ${DIRECTORY_UNIVERSE}
#    stack-auto: false
#    region-static: ap-northeast-2
#    credentials:
#      accessKey: ${S3_ACCESS_KEY}
#      secretKey: ${S3_SECRET_KEY}




