spring:
  config:
    import: optional:file:.env[.properties]

redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  timeout: 5000

cloud:
  aws:
    region: ${AWS_REGION}
    credentials:
      accessKey: ${IAM_ACCESS_KEY}
      secretKey: ${IAM_SECRET_KEY}
  s3:
    bucket: ${S3_BUCKET}
    directory:
      project: ${DIRECTORY_PROJECT}
      casting: ${DIRECTORY_CASTING}
      universe: ${DIRECTORY_UNIVERSE}
  stack-auto: false




